include ~/.config/themes/noctalia.conf

# Nivel de transparencia (0.0 es totalmente transparente, 1.0 es opaco)
background_opacity 0.85

# Habilita el desenfoque (blur) de fondo (valor positivo mayor a 0)
background_blur 32

allow_remote_control yes



# BEGIN_KITTY_THEME
# Noctalia
include current-theme.conf
# END_KITTY_THEME
