-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Acer Technologies EK220Q E3 54390D5153W01",
  mode = "1920x1080@100.00",
  position = "0x0",
  scale = 1,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
